#!/usr/bin/env python3
"""
Generate C/C++ source files for Chinese support in Ship of Harkinian.

Reads charmap + message data from scripts/chinese/message/, produces:
  1. soh/soh/z_message_CHI.cpp          — hardcoded Chinese message table
  2. soh/src/code/z_kanfont_chinese_tbl.inc  — chineseFontTbl lookup (all CharChn)
  3. soh/assets/textures/chinese_font/chinese_font.h — OTR path declarations

All-CharChn design: every CJK glyph gets its own gMsgCharChn* texture.
No Kanji reuse — the font table is self-contained.

Usage:
    uv run message/generate_assets.py
"""

from __future__ import annotations

import re
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE = Path(__file__).resolve().parent           # scripts/chinese/message/
REPO = HERE.parent.parent.parent                 # Shipwright-CN/
CHARMAP_CHN = HERE / "charmap" / "charmap_chn.txt"
MSG_CN_TXT = HERE / "txt" / "message_raw_cn_from_ique.txt"

OUT_Z_MESSAGE_CHI = REPO / "soh" / "soh" / "z_message_CHI.cpp"
OUT_Z_KANFONT_TBL = REPO / "soh" / "src" / "code" / "z_kanfont_chinese_tbl.inc"
OUT_CHINESE_FONT_H = REPO / "soh" / "assets" / "textures" / "chinese_font" / "chinese_font.h"
OUT_GLYPH_DIR = REPO / "soh" / "assets" / "custom" / "textures" / "chinese_font"
FONT_PATH = HERE / "charmap" / "SourceHanSansSC-Regular.otf"
TYPEPOS_TXT = HERE / "txt" / "message_raw_typepos.txt"

# iQue encoding range for all-CharChn
CHN_CODE_START = 0xA08C
CHN_CODE_END = 0xAC48

# Number of parameters after each control code (same as NES format)
CTRL_PARAMS = {
    0x01: 0, 0x02: 0, 0x04: 0, 0x05: 1, 0x06: 1,
    0x07: 2, 0x08: 0, 0x09: 0, 0x0A: 0, 0x0B: 0,
    0x0C: 1, 0x0D: 0, 0x0E: 1, 0x0F: 0, 0x10: 0,
    0x11: 2, 0x12: 2, 0x13: 1, 0x14: 1, 0x15: 3,
    0x16: 0, 0x17: 0, 0x18: 0, 0x19: 0, 0x1A: 0,
    0x1B: 0, 0x1C: 0, 0x1D: 0, 0x1E: 1, 0x1F: 0,
}

# The 2-byte codes for iQue button icons (0xAA9F-0xAAAB).
# These are intercepted by Font_LoadCharChinese before glyph lookup
# and mapped to NES font textures — they don't need CharChn PNGs.
BUTTON_CODES = set(range(0xAA9F, 0xAAAC))  # 0xAA9F..0xAAAB inclusive


# ---------------------------------------------------------------------------
# 1. Parse charmap
# ---------------------------------------------------------------------------

def parse_charmap(path: str) -> dict[int, str]:
    """Parse charmap_chn.txt → {code: char_display}."""
    charmap: dict[int, str] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r"^(.+?)\s*:\s*0x([0-9A-Fa-f]+)", line)
            if m:
                ch = m.group(1).strip()
                code = int(m.group(2), 16)
                charmap[code] = ch
    return charmap


# ---------------------------------------------------------------------------
# 2. Generate chinese_font.h (OTR path declarations)
# ---------------------------------------------------------------------------

def chn_char_label(ch: str) -> str:
    """Human-readable label for the charmap value. Single chars get U+XXXX,
    multi-char button labels display as-is."""
    if len(ch) == 1:
        return f"U+{ord(ch):04X} '{ch}'"
    return repr(ch)


def chn_tex_name(code: int) -> str:
    return f"gMsgCharChn{code:04X}Tex"


def chn_tex_decl(code: int) -> str:
    """Generate the OTR texture pair for one glyph code.

    Each texture needs:
      1. #define dgName "__OTR__textures/chinese_font/gName"  (OTR path string)
      2. static const ALIGN_ASSET(2) char gName[] = dgName;   (actual C variable)
    """
    name = chn_tex_name(code)
    dg_name = "d" + name  # "dgFoo" → "d" + "gFoo" (SoH convention)
    lines = [
        f'#define {dg_name} "__OTR__textures/chinese_font/{name}"',
        f"static const ALIGN_ASSET(2) char {name}[] = {dg_name};",
    ]
    return "\n".join(lines)


def generate_chinese_font_h(charmap: dict[int, str], out_path: Path):
    """Generate OTR texture header for all non-button CJK glyphs."""
    codes = sorted(c for c in charmap if c not in BUTTON_CODES
                   and CHN_CODE_START <= c <= CHN_CODE_END)

    lines = [
        "// Auto-generated by scripts/chinese/generate_assets.py",
        "// All-CharChn: every CJK glyph uses a custom gMsgCharChn* texture.",
        f"// Total: {len(codes)} glyphs + 1 fallback empty texture",
        "",
        "#ifndef TEXTURES_CHINESE_FONT_H",
        "#define TEXTURES_CHINESE_FONT_H 1",
        "",
        '#include "align_asset_macro.h"',
        "",
        "// Fallback blank glyph for undefined codes (no charmap entry)",
        '#define dgMsgCharChnEmptyTex "__OTR__textures/chinese_font/gMsgCharChnEmptyTex"',
        "static const ALIGN_ASSET(2) char gMsgCharChnEmptyTex[] = dgMsgCharChnEmptyTex;",
        "",
    ]
    for c in codes:
        ch = charmap[c]
        lines.append(chn_tex_decl(c))
        lines.append(f"// {chn_char_label(ch)}")
        lines.append("")
    lines.append("#endif")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {out_path}  ({len(codes)} entries)")


# ---------------------------------------------------------------------------
# 3. Generate z_kanfont_chinese_tbl.inc (all-CharChn lookup table)
# ---------------------------------------------------------------------------

def generate_chinese_tbl(charmap: dict[int, str], out_path: Path):
    """Generate chineseFontTbl[] — all CharChn, no Kanji reuse.

    Contiguous table: glyphIndex = character - 0xA08C.
    Undefined codes and button icons both map to gMsgCharChnEmptyTex.
    Button codes (0xAA9F-0xAAAB) are never accessed — intercepted by
    Font_LoadCharChinese before the table lookup.
    """
    total = CHN_CODE_END - CHN_CODE_START + 1
    lines = [
        "// Auto-generated by scripts/chinese/generate_assets.py",
        "// All-CharChn: every valid glyph is gMsgCharChn* (no Kanji reuse).",
        f"// Codes: 0xA08C..0x{CHN_CODE_END:04X} ({total} entries)",
        "// Undefined codes and button icons → gMsgCharChnEmptyTex (never accessed).",
        "",
        f"static const char* chineseFontTbl[{total}] = {{",
    ]

    for idx, code in enumerate(range(CHN_CODE_START, CHN_CODE_END + 1)):
        name = chn_tex_name(code)
        if code in BUTTON_CODES:
            # Intercepted by Font_LoadCharChinese — never hits table
            comment = f"button icon {chn_char_label(charmap.get(code, ''))} — uses EmptyTex"
            used_name = "gMsgCharChnEmptyTex"
        elif code in charmap:
            ch = charmap[code]
            comment = chn_char_label(ch)
            used_name = name
        else:
            comment = "undefined code — fallback to EmptyTex"
            used_name = "gMsgCharChnEmptyTex"
        lines.append(f"    {used_name}, // [{idx}] 0x{code:04X}  {comment}")

    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {out_path}  ({total} entries)")


# ---------------------------------------------------------------------------
# 4. Generate z_message_CHI.cpp (Chinese message table)
# ---------------------------------------------------------------------------

def parse_message_raw(path: str) -> dict[int, list[int]]:
    """Parse message_raw_cn_from_ique.txt → {textId: [byte, ...]}."""
    messages: dict[int, list[int]] = {}
    with open(path, encoding="utf-8") as f:
        content = f.read()
    for m in re.finditer(r"0x([0-9A-Fa-f]{4})\s*=\s*\{\s*([^}]*?)\s*\};", content):
        text_id = int(m.group(1), 16)
        byte_values = [int(b, 16) for b in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(2))]
        messages[text_id] = byte_values
    return messages


def byte_array_decl(text_id: int, data: list[int]) -> str:
    """Build a C++ array declaration for one message."""
    arr_name = f"sCHIMsgData_0x{text_id:04X}"
    hex_str = ", ".join(f"0x{b:02X}" for b in data)
    return f"static const u8 {arr_name}[] = {{ {hex_str} }};"


def read_typepos_file(path: Path) -> dict[int, int]:
    """Read textId → typePos mapping from message_raw_typepos.txt.

    Format: 0x0001 = 0x23;
    """
    typepos: dict[int, int] = {}
    if not path.exists():
        return typepos
    for m in re.finditer(
        r"0x([0-9A-Fa-f]{4})\s*=\s*0x([0-9A-Fa-f]{2});",
        path.read_text(encoding="utf-8"),
    ):
        typepos[int(m.group(1), 16)] = int(m.group(2), 16)
    return typepos


def msg_table_entry(text_id: int, data: list[int], type_pos: int = 0) -> str:
    """Build a MessageTableEntry initializer."""
    arr_name = f"sCHIMsgData_0x{text_id:04X}"
    # typePos = (textboxType << 4) | textboxYPos — copied from NTSC message
    return (f"    {{ 0x{text_id:04X}, 0x{type_pos:02X}, "
            f"(const char*){arr_name}, {len(data)} }},")


def generate_message_cpp(messages: dict[int, list[int]], out_path: Path,
                         typepos: dict[int, int] | None = None):
    """Generate z_message_CHI.cpp with all message data and table.

    If `typepos` is provided, uses the NTSC typePos for each message
    (copied from the English message table). Otherwise defaults to 0.
    """
    if typepos is None:
        typepos = {}
    sorted_ids = sorted(messages.keys())

    lines = [
        "// Auto-generated by scripts/chinese/generate_assets.py",
        f"// {len(sorted_ids)} Chinese messages from iQue ROM (corrected).",
        "",
        '#include "global.h"',
        '#include "message_data_static.h"',
        "",
        'extern "C" void OTRMessage_InitChinese(void);',
        "",
        "// #region Generated Chinese message data",
        "",
    ]

    # --- message body arrays ---
    for tid in sorted_ids:
        data = messages[tid]
        lines.append(byte_array_decl(tid, data))

    lines.append("")
    lines.append("// #endregion")
    lines.append("")
    lines.append("// #region Chinese message table")

    # --- message table ---
    lines.append("static MessageTableEntry sChiMessageTable[] = {")
    for tid in sorted_ids:
        data = messages[tid]
        tp = typepos.get(tid, 0)
        lines.append(msg_table_entry(tid, data, tp))
    # Sentinel entry
    lines.append("    { 0xFFFF, 0x00, NULL, 0 },")
    lines.append("};")

    lines.append("")
    lines.append("// #endregion")
    lines.append("")
    lines.append('extern "C" MessageTableEntry* sChiMessageEntryTablePtr;')
    lines.append("")
    lines.append('extern "C" void OTRMessage_InitChinese(void) {')
    lines.append("    sChiMessageEntryTablePtr = sChiMessageTable;")
    lines.append("}")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {out_path}  ({len(sorted_ids)} messages)")


# ---------------------------------------------------------------------------
# 5. Generate I4 PNG glyphs
# ---------------------------------------------------------------------------

GLYPH_SIZE = 16
FONT_RENDER_SIZE = 14


# Characters whose bbox-centering pushes them too high (e.g. baseline
# punctuation, thin horizontal strokes).  Extra pixels to nudge down.
_CHAR_Y_OFFSET: dict[str, int] = {
    "一": 2,   # 0xA090 — horizontal stroke sits too high
    "，": 3,   # 0xA09E — comma sits near baseline
    "。": 3,   # 0xA0A9 — full stop
    "…": 2,   # 0xA109 — ellipsis
    "．": 3,   # 0xA6B5 — full-width full stop
    "、": 3,   # 0xA6E0 — ideographic comma
}


def _render_char_i4_rgba(char: str, font) -> Image.Image:
    """Render a single character as a 16×16 RGBA image.

    Uses anti-aliased rendering with the font, centered in the glyph box.
    Output is RGBA mode (not grayscale) for maximum OTR tool compatibility.
    Each pixel = (gray, gray, gray, 255).
    """
    img = Image.new("L", (GLYPH_SIZE, GLYPH_SIZE), 0)
    draw = ImageDraw.Draw(img)

    bbox = draw.textbbox((0, 0), char, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    x = (GLYPH_SIZE - w) // 2 - bbox[0]
    y = (GLYPH_SIZE - h) // 2 - bbox[1]
    y += _CHAR_Y_OFFSET.get(char, 0)

    draw.text((x, y), char, fill=255, font=font)

    # Convert L (grayscale) → RGBA
    rgba = Image.new("RGBA", (GLYPH_SIZE, GLYPH_SIZE), (0, 0, 0, 0))
    gray_pixels = img.load()
    rgba_pixels = rgba.load()
    for py in range(GLYPH_SIZE):
        for px in range(GLYPH_SIZE):
            g = gray_pixels[px, py]
            rgba_pixels[px, py] = (g, g, g, 255)
    return rgba


def generate_i4_glyphs(charmap: dict[int, str], out_dir: Path):
    """Generate I4 16×16 RGBA PNG glyphs for every non-button CJK character.

    Skips characters already present on disk.
    Also generates the fallback gMsgCharChnEmptyTex.i4.png (blank 16×16).
    """
    if not HAS_PIL:
        print("  Pillow not installed — skipping glyph generation.")
        print("  Install: uv add pillow")
        return

    font_path = str(FONT_PATH)
    if not Path(font_path).exists():
        print(f"  Font not found: {font_path} — skipping glyph generation.")
        return

    font = ImageFont.truetype(font_path, FONT_RENDER_SIZE)
    out_dir.mkdir(parents=True, exist_ok=True)

    codes = sorted(c for c in charmap
                   if c not in BUTTON_CODES and CHN_CODE_START <= c <= CHN_CODE_END)
    total = len(codes)
    generated = 0
    skipped = 0

    for i, code in enumerate(codes):
        png_name = f"{chn_tex_name(code)}.i4.png"
        png_path = out_dir / png_name

        if png_path.exists():
            skipped += 1
            continue

        ch = charmap[code]
        if len(ch) != 1:
            continue  # skip multi-char labels

        img = _render_char_i4_rgba(ch, font)
        img.save(png_path, "PNG")
        generated += 1

        if (generated + skipped) % 200 == 0 or i == total - 1:
            print(f"  [{i+1}/{total}] {generated} new, {skipped} skipped")

    # Generate fallback empty texture
    empty_path = out_dir / "gMsgCharChnEmptyTex.i4.png"
    if not empty_path.exists():
        empty_img = Image.new("RGBA", (GLYPH_SIZE, GLYPH_SIZE), (0, 0, 0, 0))
        empty_img.save(empty_path, "PNG")
        generated += 1

    print(f"  Done: {generated} generated, {skipped} skipped, {total} total glyphs")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=== Generate Chinese assets for Ship of Harkinian ===\n")

    # Parse source data
    print("1. Parsing charmap...")
    charmap = parse_charmap(CHARMAP_CHN)
    print(f"   {len(charmap)} characters")

    print("\n2. Parsing CN messages...")
    messages = parse_message_raw(MSG_CN_TXT)
    print(f"   {len(messages)} messages")

    print("\n3. Reading typePos from message_raw_typepos.txt ...")
    typepos_map = read_typepos_file(TYPEPOS_TXT)
    print(f"   {len(typepos_map)} typePos entries")

    # Generate outputs
    print("\n4. Generating chinese_font.h ...")
    generate_chinese_font_h(charmap, OUT_CHINESE_FONT_H)

    print("\n5. Generating z_kanfont_chinese_tbl.inc ...")
    generate_chinese_tbl(charmap, OUT_Z_KANFONT_TBL)

    print("\n6. Generating z_message_CHI.cpp ...")
    generate_message_cpp(messages, OUT_Z_MESSAGE_CHI, typepos_map)

    print("\n7. Generating I4 glyph PNGs ...")
    generate_i4_glyphs(charmap, OUT_GLYPH_DIR)

if __name__ == "__main__":
    main()
